services:
  kinofun:
    image: nginx:alpine
    container_name: kinofun
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8081:80"
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./kinofun.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/letsencrypt:ro
